// registration
export const REGISTRATION_REQUEST = 'REGISTRATION_REQUEST';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR';

// authenticate
export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';
export const SIGN_OUT_REQUEST = 'SIGN_OUT_REQUEST';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_ERROR = 'SIGN_OUT_ERROR';

// validateToken
export const VALIDATE_TOKEN_REQUEST = 'VALIDATE_TOKEN_REQUEST';
export const VALIDATE_TOKEN_ERROR = 'VALIDATE_TOKEN_ERROR';

// oAuthenticate
export const OAUTHENTICATE_REQUEST = 'OAUTHENTICATE_REQUEST';

// token
export const UPDATE_HEADERS = 'UPDATE_HEADERS';

// async storage
export const SET_ITEM_ASYNC_STORAGE = 'SET_ITEM_ASYNC_STORAGE';

// posts
export const GET_REFRESH_POSTS_REQUEST = 'GET_REFRESH_POSTS_REQUEST';
export const GET_NEXT_POSTS_REQUEST = 'GET_NEXT_POSTS_REQUEST';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_ERROR = 'GET_POSTS_ERROR';

export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_ERROR = 'CREATE_POST_ERROR';

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_ERROR = 'DELETE_POST_ERROR';

export const UPDATE_POST_REQUEST = 'UPDATE_POST_REQUEST';
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';
export const UPDATE_POST_ERROR = 'UPDATE_POST_ERROR';

//quotes
export const UPDATE_QUOTES = 'UPDATE_QUOTES';

//quotesSettings
export const UPDATE_QUOTES_SETTINGS = 'UPDATE_QUOTES_SETTINGS';

// favorites
export const GET_FAVORITES_REQUEST = 'GET_FAVORITES_REQUEST';
export const GET_FAVORITES_SUCCESS = 'GET_FAVORITES_SUCCESS';
export const GET_FAVORITES_ERROR = 'GET_FAVORITES_ERROR';

export const UPDATE_FAVORITE_REQUEST = 'UPDATE_FAVORITE_REQUEST';
export const UPDATE_FAVORITE_SUCCESS = 'UPDATE_FAVORITE_SUCCESS';
export const UPDATE_FAVORITE_ERROR = 'UPDATE_FAVORITE_ERROR';

// platform
export const CONNECT_PLATFORM_REQUEST = 'CONNECT_PLATFORM_REQUEST';
export const CONNECT_PLATFORM_SUCCESS = 'CONNECT_PLATFORM_SUCCESS';
export const CONNECT_PLATFORM_ERROR = 'CONNECT_PLATFORM_ERROR';

export const DISCONNECT_PLATFORM_REQUEST = 'DISCONNECT_PLATFORM_REQUEST';
export const DISCONNECT_PLATFORM_SUCCESS = 'DISCONNECT_PLATFORM_SUCCESS';
export const DISCONNECT_PLATFORM_ERROR = 'DISCONNECT_PLATFORM_ERROR';

export const UPDATE_USER_STATISTICS = 'UPDATE_USER_STATISTICS';

// brokers
export const AUTHORIZE_BROKER_REQUEST = 'AUTHORIZE_BROKER_REQUEST';
export const AUTHORIZE_BROKER_SUCCESS = 'AUTHORIZE_BROKER_SUCCESS';
export const AUTHORIZE_BROKER_ERROR = 'AUTHORIZE_BROKER_ERROR';

export const REGISTER_BROKER_REQUEST = 'REGISTER_BROKER_REQUEST';
export const REGISTER_BROKER_SUCCESS = 'REGISTER_BROKER_SUCCESS';
export const REGISTER_BROKER_ERROR = 'REGISTER_BROKER_ERROR';

export const FORGOT_PASS_BROKER_REQUEST = 'FORGOT_PASS_BROKER_REQUEST';
export const FORGOT_PASS_BROKER_SUCCESS = 'FORGOT_PASS_BROKER_SUCCESS';
export const FORGOT_PASS_BROKER_ERROR = 'FORGOT_PASS_BROKER_ERROR';

export const DISCONNECT_BROKER_SUCCESS = 'DISCONNECT_BROKER_SUCCESS';

export const DISCONNECT_TOKEN_SUCCESS = 'DISCONNECT_BROKER_SUCCESS';

// userStatus
export const UPDATE_USERS_STATUS = 'UPDATE_USERS_STATUS';

// deals
export const GET_OPEN_DEALS_REQUEST = 'GET_OPEN_DEALS_REQUEST';
export const GET_OPEN_DEALS_SUCCESS = 'GET_OPEN_DEALS_SUCCESS';
export const GET_OPEN_DEALS_ERROR = 'GET_OPEN_DEALS_ERROR';

export const GET_CLOSE_DEALS_REQUEST = 'GET_CLOSE_DEALS_REQUEST';
export const GET_CLOSE_DEALS_SUCCESS = 'GET_CLOSE_DEALS_SUCCESS';
export const GET_CLOSE_DEALS_ERROR = 'GET_CLOSE_DEALS_ERROR';

export const GET_POST_DEALS_REQUEST = 'GET_POST_DEALS_REQUEST';
export const GET_POST_DEALS_SUCCESS = 'GET_POST_DEALS_SUCCESS';
export const GET_POST_DEALS_ERROR = 'GET_POST_DEALS_ERROR';

export const CREATE_OPEN_DEAL_REQUEST = 'CREATE_OPEN_DEAL_REQUEST';
export const CREATE_OPEN_DEAL_SUCCESS = 'CREATE_OPEN_DEAL_SUCCESS';
export const CREATE_OPEN_DEAL_ERROR = 'CREATE_OPEN_DEAL_ERROR';

export const CHANGE_OPEN_DEAL_REQUEST = 'CHANGE_OPEN_DEAL_REQUEST';
export const CHANGE_OPEN_DEAL_SUCCESS = 'CHANGE_OPEN_DEAL_SUCCESS';
export const CHANGE_OPEN_DEAL_ERROR = 'CHANGE_OPEN_DEAL_ERROR';

export const CLOSE_OPEN_DEAL_REQUEST = 'CLOSE_OPEN_DEAL_REQUEST';
export const CLOSE_OPEN_DEAL_SUCCESS = 'CLOSE_OPEN_DEAL_SUCCESS';
export const CLOSE_OPEN_DEAL_ERROR = 'CLOSE_OPEN_DEAL_ERROR';

// likes actions
