// registration
export const REGISTRATION_REQUEST = 'REGISTRATION_REQUEST';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR';

// authenticate
export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';
export const SIGN_OUT_REQUEST = 'SIGN_OUT_REQUEST';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_ERROR = 'SIGN_OUT_ERROR';

// validateToken
export const VALIDATE_TOKEN_REQUEST = 'VALIDATE_TOKEN_REQUEST';
export const VALIDATE_TOKEN_ERROR = 'VALIDATE_TOKEN_ERROR';

// oAuthenticate
export const OAUTHENTICATE_REQUEST = 'OAUTHENTICATE_REQUEST';

// token
export const UPDATE_HEADERS = 'UPDATE_HEADERS';

// async storage
export const SET_ITEM_ASYNC_STORAGE = 'SET_ITEM_ASYNC_STORAGE';

// posts
export const GET_REFRESH_POSTS_REQUEST = 'GET_REFRESH_POSTS_REQUEST';
export const GET_NEXT_POSTS_REQUEST = 'GET_NEXT_POSTS_REQUEST';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_ERROR = 'GET_POSTS_ERROR';

export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_ERROR = 'CREATE_POST_ERROR';

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_ERROR = 'DELETE_POST_ERROR';

export const UPDATE_POST_REQUEST = 'UPDATE_POST_REQUEST';
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';
export const UPDATE_POST_ERROR = 'UPDATE_POST_ERROR';

//quotes
export const UPDATE_QUOTES = 'UPDATE_QUOTES';

//quotesSettings
export const UPDATE_QUOTES_SETTINGS = 'UPDATE_QUOTES_SETTINGS';

// favorite
export const GET_FAVORITES_REQUEST = 'GET_FAVORITES_REQUEST';
export const GET_FAVORITES_SUCCESS = 'GET_FAVORITES_SUCCESS';
export const GET_FAVORITES_ERROR = 'GET_FAVORITES_ERROR';

export const UPDATE_FAVORITE_REQUEST = 'UPDATE_FAVORITE_REQUEST';
export const UPDATE_FAVORITE_SUCCESS = 'UPDATE_FAVORITE_SUCCESS';
export const UPDATE_FAVORITE_ERROR = 'UPDATE_FAVORITE_ERROR';
